### ISSUE TITLE
Selected text does not move by one character

### ISSUE THREAD

**Issue by MartinBulla** [colinta/SublimeMoveText#14]
I am using your package, together with your key binding on Mac. If I select a text (in bold),
 
1 TEST
2    **test test**
3    test test

and execute the key binding, instead of moving one character right, it does the following:

1 TEST
2    
3 **test test**    test test

The key binding for moving one character left works in this case. However, if I select both "# test test"s neither of the two works. The move to the right does nothing and the move to the left produces this:

1 TEST    **test test**
2    **test test**

Curious to hear your thoughts.

Best,
Martin

**Comment by colinta** [comment]
This looks.. right to me, if the second line is selected, and you move it to the right, it moves to the next line.  Did you expect it to insert spaces and keep the text on the same line?

If you could, use "code fences" (triple backticks) to format the lines, like this:

###### Setup:
```
TEST
*selected text*
test
```

###### After pressing "command+right"
```
TEST

*selected text*test
```

###### Expected behavior:
```
TEST
?
test
```

**Comment by MartinBulla** [comment]
Thanks you for your reply. Indeed, I have expected to insert spaces and keep the text on the same line (same way as cmd+] or cmd+[ works with tabs). Could you add this functionality?
