### ISSUE TITLE
Add move by word

### ISSUE THREAD

**Issue by certainlyakey** [colinta/SublimeMoveText#8]
Could you please consider adding a command to move selected text by words - so that when executing it the text would move not by character but would jump through words. 
So that if I want to move the word `consectetur` in 

`Lorem ipsum dolor sit amet, consectetur adipisicing elit`

to the very end, it would require 2 keystrokes, not 17.
Would be very useful for plain text editing (Markdown etc.). 
Thank you!

**Comment by Kristinita** [comment]
+1. It would be nice, if you add move by words. This is a useful feature.

Thanks.

**Comment by colinta** [comment]
@Kristinita I'm all for this feature, except *I personally* don't think I would use it, and I don't have the time to add it.  I really encourage you to look at the Sublime Text API, it's great, and really simple.  Easy to hack on.

To make this feature easier to add, I made some changes in `move_text.py`.  It now accepts `selections`, so that instead of always using all the cursor selections, you can pass in just the regions you want to edit.

So at this point, if you want to add this feature, you just need to:

- [ ] Create two new commands, `class MoveTextRightWordCommand(MoveTextHorizCommand)` and `MoveTextLeftWord...`
- [ ] Iterate over each selection, and for each one, determine the number of characters that the text should be moved. `for sel in self.view.sel(): ... cursor = sel.end() or sel.begin() ... char = self.view.substr(cursor) ...` and then scan left or right until char is a space or not a letter, or whatever
- [ ] Pass that `number_of_characters` and the selection region to `move_text_horiz`, and it will handle the rest

If you start this feature I'll definitely help debug and answer questions! :smiley:
